baseURL = 'https://m82-project.org/'

SectionPagesMenu = "main"
defaultContentLanguage = "fr"
theme = "gohugo-theme-ananke"
[languages]
    [languages.en]
    title = "Ananke"
    weight = 1
    # languageDirection = 'rtl' for Right-To-Left languages
    [languages.fr]
    weight = 2
    contentDir = "content"
    

[[params.ananke_socials]]
name = "linkedin"
url = ""
[[params.ananke_socials]]
name = "github"
url = ""

