baseURL = 'https://m82-project.org'

SectionPagesMenu = "main"
defaultContentLanguage = "fr"
theme = "gohugo-theme-ananke"

[params]
  favicon= "images/favicon.ico"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[languages]
    [languages.fr]
    title = "M82 Project"
    weight = 5
    contentDir = "content"

[params.ananke.social.share]
networks = [
  "github",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "github",
  "linkedin"
]

[params.ananke.social]
[params.ananke.social.github]
profilelink = "https://www.github.com/M82-Project/"

[params.ananke.social.linkedin]
profilelink = "https://www.linkedin.com/company/m82-project/"


