baseURL = 'https://chipper-klepon-ab7771.netlify.app'

SectionPagesMenu = "main"
defaultContentLanguage = "fr"
theme = "gohugo-theme-ananke"
site_logo = "images/M82_N.jpg"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[languages]
    [languages.fr]
    title = "M82 Project"
    weight = 1
    contentDir = "content"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/company/m82-project/"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/M82-project/"

