baseURL = 'https://chipper-klepon-ab7771.netlify.app'

SectionPagesMenu = "main"
defaultContentLanguage = "fr"
theme = "gohugo-theme-ananke"
site_logo = "images/M82_N.jpg"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[languages]
    [languages.en]
    title = "M82 Project"
    weight = 1
    # languageDirection = 'rtl' for Right-To-Left languages
    [languages.fr]
    title = "M82 Project"
    weight = 1
    contentDir = "content"

[[params.ananke_socials]]
name = "linkedin"
url = ""
[[params.ananke_socials]]
name = "github"
url = ""

