name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Initialisez les sous-modules et mettez-les à jour récursivement
          submodules: 'recursive'

      - name: Build Hugo site
        uses: docker://hugomods/hugo  # Remplacez par la version de Hugo que vous souhaitez utiliser
        with:
          args: "server --bind 0.0.0.0 --baseURL=http://localhost --port 80"

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: public/
